name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
        
      #- name: Install dependencies
        #run: |
        #  python -m pip install --upgrade pip
        #  pip install -r requirements.txt
      # - name: Test with pytest
      #   run: |
      #     pip install pytest pytest-cov
      #     pytest src/model_demo/tests/test_model.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

#  pytest tests.py: Runs tests in the tests.py file.
#  --doctest-modules: Enables doctest discovery, running tests embedded in docstrings of Python modules.
#  --junitxml=junit/test-results.xml: Generates a JUnit-style XML report at junit/test-results.xml for CI integration.
#  --cov=com: Measures code coverage for the com package or directory.
#  --cov-report=xml: Generates a coverage report in XML format (typically coverage.xml).
#  --cov-report=html: Generates an HTML coverage report (typically in htmlcov/ directory).
